//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.OrderTab {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblid;
		protected global::System.Web.UI.WebControls.TextBox txtMemberID;
		protected global::System.Web.UI.WebControls.TextBox txtMemberName;
		protected global::System.Web.UI.WebControls.TextBox txtMemberPhone;
		protected global::System.Web.UI.WebControls.TextBox txtMemberPhone1;
		protected global::System.Web.UI.WebControls.TextBox txtMemberAdd;
		protected global::System.Web.UI.WebControls.TextBox txtOrderdate;
		protected global::System.Web.UI.WebControls.TextBox txtOrderNumber;
		protected global::System.Web.UI.WebControls.TextBox txtStaffmemberID;
		protected global::System.Web.UI.WebControls.TextBox txtStaffmembername;
		protected global::System.Web.UI.WebControls.TextBox txtUserTabID;
		protected global::System.Web.UI.WebControls.TextBox txtPhotoID;
		protected global::System.Web.UI.WebControls.TextBox txtvalidity;
		protected global::System.Web.UI.WebControls.TextBox txtprogress;
		protected global::System.Web.UI.WebControls.TextBox txtDeposit;
		protected global::System.Web.UI.WebControls.TextBox txtAllMoney;
		protected global::System.Web.UI.WebControls.TextBox txtalllength;
		protected global::System.Web.UI.WebControls.TextBox txtImperial;
		protected global::System.Web.UI.WebControls.TextBox txtQhWidth;
		protected global::System.Web.UI.WebControls.TextBox txtBeizhuwg;
		protected global::System.Web.UI.WebControls.TextBox txtBeizhuzz;
		protected global::System.Web.UI.WebControls.TextBox txtZengsong;
		protected global::System.Web.UI.WebControls.TextBox txtZhuangtai1;
		protected global::System.Web.UI.WebControls.TextBox txtZhuangtai2;
		protected global::System.Web.UI.WebControls.TextBox txtBy1;
		protected global::System.Web.UI.WebControls.TextBox txtBy2;
		protected global::System.Web.UI.WebControls.TextBox txtBy3;
		protected global::System.Web.UI.WebControls.TextBox txtBy4;
		protected global::System.Web.UI.WebControls.TextBox txtBy5;
		protected global::System.Web.UI.WebControls.TextBox txtBy6;
		protected global::System.Web.UI.WebControls.TextBox txtBy7;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
