//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.OrderTab {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblMemberID;
	protected global::System.Web.UI.WebControls.Label lblMemberName;
	protected global::System.Web.UI.WebControls.Label lblMemberPhone;
	protected global::System.Web.UI.WebControls.Label lblMemberPhone1;
	protected global::System.Web.UI.WebControls.Label lblMemberAdd;
	protected global::System.Web.UI.WebControls.Label lblOrderdate;
	protected global::System.Web.UI.WebControls.Label lblOrderNumber;
	protected global::System.Web.UI.WebControls.Label lblStaffmemberID;
	protected global::System.Web.UI.WebControls.Label lblStaffmembername;
	protected global::System.Web.UI.WebControls.Label lblUserTabID;
	protected global::System.Web.UI.WebControls.Label lblPhotoID;
	protected global::System.Web.UI.WebControls.Label lblvalidity;
	protected global::System.Web.UI.WebControls.Label lblprogress;
	protected global::System.Web.UI.WebControls.Label lblDeposit;
	protected global::System.Web.UI.WebControls.Label lblAllMoney;
	protected global::System.Web.UI.WebControls.Label lblalllength;
	protected global::System.Web.UI.WebControls.Label lblImperial;
	protected global::System.Web.UI.WebControls.Label lblQhWidth;
	protected global::System.Web.UI.WebControls.Label lblBeizhuwg;
	protected global::System.Web.UI.WebControls.Label lblBeizhuzz;
	protected global::System.Web.UI.WebControls.Label lblZengsong;
	protected global::System.Web.UI.WebControls.Label lblZhuangtai1;
	protected global::System.Web.UI.WebControls.Label lblZhuangtai2;
	protected global::System.Web.UI.WebControls.Label lblBy1;
	protected global::System.Web.UI.WebControls.Label lblBy2;
	protected global::System.Web.UI.WebControls.Label lblBy3;
	protected global::System.Web.UI.WebControls.Label lblBy4;
	protected global::System.Web.UI.WebControls.Label lblBy5;
	protected global::System.Web.UI.WebControls.Label lblBy6;
	protected global::System.Web.UI.WebControls.Label lblBy7;


       
    }
}
