//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Department {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtdepartmentname;
		protected global::System.Web.UI.WebControls.TextBox txtBeizhu;
		protected global::System.Web.UI.WebControls.TextBox txtBY1;
		protected global::System.Web.UI.WebControls.TextBox txtBY2;
		protected global::System.Web.UI.WebControls.TextBox txtBY3;
		protected global::System.Web.UI.WebControls.TextBox txtBY4;
		protected global::System.Web.UI.WebControls.TextBox txtBY5;
		protected global::System.Web.UI.WebControls.TextBox txtBY6;
		protected global::System.Web.UI.WebControls.TextBox txtBY7;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
