//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Categorytab {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblBeizhu;
	protected global::System.Web.UI.WebControls.Label lblBY1;
	protected global::System.Web.UI.WebControls.Label lblBY2;
	protected global::System.Web.UI.WebControls.Label lblBY3;
	protected global::System.Web.UI.WebControls.Label lblBY4;
	protected global::System.Web.UI.WebControls.Label lblBY5;
	protected global::System.Web.UI.WebControls.Label lblBY6;
	protected global::System.Web.UI.WebControls.Label lblBY7;


       
    }
}
