//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.Position {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lblname;
	protected global::System.Web.UI.WebControls.Label lblbeizhu;
	protected global::System.Web.UI.WebControls.Label lblBy1;
	protected global::System.Web.UI.WebControls.Label lblBy2;
	protected global::System.Web.UI.WebControls.Label lblBy3;
	protected global::System.Web.UI.WebControls.Label lblBy4;
	protected global::System.Web.UI.WebControls.Label lblBy5;
	protected global::System.Web.UI.WebControls.Label lblBy6;
	protected global::System.Web.UI.WebControls.Label lblBy7;


       
    }
}
