//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maticsoft.Web.ContractTab {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtOrderNumber;
		protected global::System.Web.UI.WebControls.TextBox txtCommodityID;
		protected global::System.Web.UI.WebControls.TextBox txtbeizhu;
		protected global::System.Web.UI.WebControls.TextBox txtBy1;
		protected global::System.Web.UI.WebControls.TextBox txtBy2;
		protected global::System.Web.UI.WebControls.TextBox txtBy3;
		protected global::System.Web.UI.WebControls.TextBox txtBy4;
		protected global::System.Web.UI.WebControls.TextBox txtBy5;
		protected global::System.Web.UI.WebControls.TextBox txtBy6;
		protected global::System.Web.UI.WebControls.TextBox txtBy7;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
